# =============================================================================
# 00_distance_v4.1.R
#
# Test simulation pipeline for line-transect distance sampling, mirroring
# the v4.1 spatial-sim conventions for the underlying density field.
#
# Per species (humpback whale and Pacific white-sided dolphin), this
# script:
#
#   1. Simulates a zero-mean GP density surface (animals/km^2) using the
#      v4.1 domain, bathymetry, and species-specific GP hyperparameters.
#   2. Converts the animal-density surface to a group-density surface:
#         lambda_groups = lambda_animals / mean_group_size,
#      with mean group sizes 2 (humpback) and 50 (PWSD).
#   3. Lays down systematic parallel E-W transects, splits them into
#      10-km segments, and simulates group sightings from a SPECIES-
#      SPECIFIC half-normal detection function. PWSD's detection
#      function additionally has a group-size covariate
#         log(sigma_g) = log_sigma_0 + beta_size * (s_g - s_centre)
#      so larger groups are more detectable. Humpback uses a single
#      sigma (constant group size = 2 means no covariate signal).
#   4. PWSD groups get sizes drawn from a zero-truncated NB(mu=50,
#      size=5) so the group-size covariate is identifiable. Humpback
#      groups all have size 2.
#   5. Fits distance/distance_hn_dens_v4.1.stan to the simulated
#      observations - one fit per species. The Stan model accepts
#      species-specific priors on log_lambda_s (now passed as data,
#      not hardcoded), per-species priors on the NB group-size
#      parameters, and a use_size_covar flag for whether to include
#      the detection covariate.
#   6. Writes diagnostic plots and a parameter-recovery table to
#      outputs/distance_v4.1/. Plots include a prior-vs-posterior
#      density overlay for animal density D = lambda_s * mu_s.
#
# Run from the project root:
#   Rscript distance/00_distance_v4.1.R
# =============================================================================

suppressPackageStartupMessages({
  library(tidyverse)
  library(MASS)
  library(cmdstanr)
  library(posterior)
  library(patchwork)
  library(viridis)
})

set.seed(7)   # bumped from 42; previous seed produced an unusually
              # high count of PWSD detections (~2.6 sigma above
              # expected) that pushed lambda_s posterior off truth.

# -----------------------------------------------------------------------------
# Load empirical group-size pools (real survey sightings) for the
# simulated group-size draws. Generated by scripts/getGrpSz.R from
# Data/sightings.csv (humpback = spcode 76, PWSD = spcode 22).
# -----------------------------------------------------------------------------
load("distance/humpback_grpsz.RData")    # populates si.humpback
load("distance/pwsd_grpsz.RData")        # populates si.pwsd
gs_pool_humpback <- as.integer(si.humpback)
gs_pool_pwsd     <- as.integer(si.pwsd)
cat(sprintf("Empirical group-size pools:\n"))
cat(sprintf("  humpback: n=%d, mean=%.2f, median=%.0f, range [%d, %d]\n",
            length(gs_pool_humpback), mean(gs_pool_humpback),
            median(gs_pool_humpback),
            min(gs_pool_humpback), max(gs_pool_humpback)))
cat(sprintf("  pwsd    : n=%d, mean=%.2f, median=%.0f, range [%d, %d]\n",
            length(gs_pool_pwsd), mean(gs_pool_pwsd),
            median(gs_pool_pwsd),
            min(gs_pool_pwsd), max(gs_pool_pwsd)))

OUTPUT_DIR <- "outputs/distance_v4.1"
dir.create(OUTPUT_DIR, showWarnings = FALSE, recursive = TRUE)

# -----------------------------------------------------------------------------
# 0. Helpers
# -----------------------------------------------------------------------------

erf <- function(x) 2 * pnorm(x * sqrt(2)) - 1

aniso_cov <- function(coords, sigma, lx, ly, lz, jitter = 1e-6) {
  d2 <- outer(coords[, 1], coords[, 1], function(a, b) ((a - b) / lx)^2) +
        outer(coords[, 2], coords[, 2], function(a, b) ((a - b) / ly)^2) +
        outer(coords[, 3], coords[, 3], function(a, b) ((a - b) / lz)^2)
  sigma * sigma * exp(-0.5 * d2) + diag(jitter, nrow(d2))
}

# Zero-truncated negative binomial draw with mean mu and shape size.
rnbinom_zt <- function(n, mu, size) {
  out <- integer(n)
  for (i in seq_len(n)) {
    repeat {
      r <- rnbinom(1, mu = mu, size = size)
      if (r > 0L) { out[i] <- r; break }
    }
  }
  out
}

# -----------------------------------------------------------------------------
# 1. Domain (matches v4.1)
# -----------------------------------------------------------------------------

X_km_max     <- 500
Y_km_max     <- 1270
rotation_deg <- 25
rot          <- rotation_deg * pi / 180

X_prime_fn <- function(X_km, Y_km) {
  raw <- cos(rot) * (X_km / X_km_max) + sin(rot) * (Y_km / Y_km_max)
  300 * raw / (cos(rot) + sin(rot))
}

bathy_mean_fn <- function(X_km, Y_km) {
  xp      <- X_prime_fn(X_km, Y_km)
  abyssal <- 2500
  shelf   <- 80
  pmax(abyssal + (shelf - abyssal) / (1 + exp(-0.06 * (xp - 180))), 10)
}

# -----------------------------------------------------------------------------
# 2. Species (humpback + PWSD), each with its own detection function and
#    its own log_lambda_s / mu_s priors.
# -----------------------------------------------------------------------------
#
# Detection-function notes:
#   * Humpback: large surface-active baleen whale - readily detected at
#     several km. sigma_det = 2.5 km. No group-size covariate
#     (use_size_covar = 0). All groups size 2.
#   * PWSD: smaller delphinid, but very gregarious. sigma at the
#     reference group size of 50 = 1.5 km. beta_size = 0.01 per
#     individual on log(sigma), so a group of 100 has sigma ~ 2.5 km
#     (1.5 * exp(0.01*50)) and a group of 25 has sigma ~ 1.16 km.
#     Group sizes drawn from zero-truncated NB(mu=50, size=5)
#     (sd ~ 24, range ~5-150).
#
# log_lambda_s prior centring: chosen to be moderately informative around
# a rough "what we'd guess from the data before fitting" value, with
# enough sd that the data dominates the posterior.

humpback_mean_gs <- mean(gs_pool_humpback)   # ~1.72
pwsd_mean_gs     <- mean(gs_pool_pwsd)       # ~42.75

species_params <- list(

  humpback = list(
    common_name      = "Humpback whale",
    sigma            = 1.0,
    lx               = 50,        # km
    ly               = 300,       # km
    lz               = 100,       # m
    mu               = log(0.004),# log animals/km^2
    mean_group_size  = humpback_mean_gs,
    group_size_dist  = "empirical",
    group_size_pool  = gs_pool_humpback,

    # Detection function
    sigma_det        = 2.5,       # km, at s = s_centre
    use_size_covar   = 0L,
    beta_size_truth  = 0.0,       # ignored under use_size_covar = 0
    s_centre         = humpback_mean_gs,

    # Stan priors (now data, per-species)
    log_sigma_prior_mean    = log(2.5),
    log_sigma_prior_sd      = 0.6,
    beta_size_prior_mean    = 0.0,
    beta_size_prior_sd      = 0.05,           # tight near 0 since not used
    # Gamma mean ~= empirical mean, mode ~= mean - 1/rate.
    # shape = 4 -> sd = 0.5 * mean. Mildly informative.
    mu_s_prior_shape        = 4,
    mu_s_prior_rate         = 4 / humpback_mean_gs,
    phi_s_prior_shape       = 1,
    phi_s_prior_rate        = 0.1,
    log_lambda_s_prior_mean = log(0.004 / humpback_mean_gs),
    log_lambda_s_prior_sd   = 1.5,
    S_max                   = 50L              # NB tail upper bound
  ),

  pwsd = list(
    common_name      = "Pacific white-sided dolphin",
    sigma            = 1.3,
    lx               = 40,
    ly               = 300,
    lz               = 300,
    mu               = log(0.032),
    mean_group_size  = pwsd_mean_gs,
    group_size_dist  = "empirical",
    group_size_pool  = gs_pool_pwsd,

    # Detection function (with group-size covariate)
    sigma_det        = 1.5,                   # km, at s = s_centre
    use_size_covar   = 1L,
    beta_size_truth  = 0.01,                  # per-individual log(sigma) increment
    s_centre         = pwsd_mean_gs,

    # Stan priors
    log_sigma_prior_mean    = log(1.5),
    log_sigma_prior_sd      = 0.6,
    beta_size_prior_mean    = 0.0,
    beta_size_prior_sd      = 0.05,
    mu_s_prior_shape        = 4,
    mu_s_prior_rate         = 4 / pwsd_mean_gs,
    phi_s_prior_shape       = 1,
    phi_s_prior_rate        = 0.1,
    log_lambda_s_prior_mean = log(0.032 / pwsd_mean_gs),
    log_lambda_s_prior_sd   = 1.5,
    # Empirical PWSD group sizes go up to ~450; need plenty of NB tail
    # for the Jensen integration. 1000 covers all plausible posteriors.
    S_max                   = 1000L
  )
)

w <- 5.0   # truncation distance, km, shared across species

# -----------------------------------------------------------------------------
# 3. Survey design: 25 systematic E-W transects, 10 km segments
# -----------------------------------------------------------------------------

n_transects        <- 25
seg_length         <- 10
n_seg_per_transect <- floor(X_km_max / seg_length)

transect_Y <- seq(Y_km_max / (2 * n_transects),
                  Y_km_max - Y_km_max / (2 * n_transects),
                  length.out = n_transects)

segments <- expand.grid(
  transect_id = seq_len(n_transects),
  seg_idx     = seq_len(n_seg_per_transect)
) |>
  dplyr::mutate(
    X_mid    = (seg_idx - 0.5) * seg_length,
    Y_mid    = transect_Y[transect_id],
    Z_bathy  = bathy_mean_fn(X_mid, Y_mid),
    seg_id   = dplyr::row_number(),
    seg_l    = seg_length
  )

n_seg_total <- nrow(segments)
total_effort_km <- sum(segments$seg_l)

cat(sprintf("Survey: %d transects x %d segments = %d segments\n",
            n_transects, n_seg_per_transect, n_seg_total))
cat(sprintf("  total effort = %.0f km, surveyed area = %.0f km^2\n",
            total_effort_km, total_effort_km * 2 * w))
cat(sprintf("  truncation distance w = %.2f km\n\n", w))

# -----------------------------------------------------------------------------
# 4. Per-species simulation + fit
# -----------------------------------------------------------------------------

stan_file <- "distance/distance_hn_dens_v4.1.stan"
mod <- cmdstan_model(stan_file, cpp_options = list(stan_threads = TRUE))

results <- list()

for (sp_key in names(species_params)) {
  p <- species_params[[sp_key]]
  cat(sprintf("\n======================================================\n"))
  cat(sprintf("=== %s\n", p$common_name))
  cat(sprintf("======================================================\n"))

  # ------------- 4a. Draw GP at segment midpoints -----------------------------
  coords <- as.matrix(segments[, c("X_mid", "Y_mid", "Z_bathy")])
  K      <- aniso_cov(coords, p$sigma, p$lx, p$ly, p$lz)
  f_seg  <- as.vector(MASS::mvrnorm(1, mu = rep(0, n_seg_total), Sigma = K))

  lambda_animals <- exp(p$mu + f_seg)
  lambda_groups  <- lambda_animals / p$mean_group_size

  cat(sprintf("\n  spatial truth (mean across %d segments):\n", n_seg_total))
  cat(sprintf("    lambda_animals = %.4f animals/km^2\n", mean(lambda_animals)))
  cat(sprintf("    lambda_groups  = %.4f groups/km^2\n",  mean(lambda_groups)))
  cat(sprintf("    detection: sigma_det = %.2f km, use_size_covar = %d\n",
              p$sigma_det, p$use_size_covar))
  if (p$use_size_covar == 1L) {
    cat(sprintf("    beta_size_truth = %.4f, s_centre = %g\n",
                p$beta_size_truth, p$s_centre))
  }

  # ------------- 4b. Simulate group sightings ---------------------------------

  expected_groups   <- lambda_groups * 2 * w * seg_length
  n_groups_in_strip <- rpois(n_seg_total, expected_groups)

  detect_rows <- vector("list", n_seg_total)
  for (i in seq_len(n_seg_total)) {
    n_strip <- n_groups_in_strip[i]
    if (n_strip == 0L) next
    x_true <- runif(n_strip, 0, w)
    # Group sizes for this segment's groups
    if (p$group_size_dist == "empirical") {
      s_strip <- sample(p$group_size_pool, n_strip, replace = TRUE)
    } else if (p$group_size_dist == "constant") {
      s_strip <- rep(p$mean_group_size, n_strip)
    } else if (p$group_size_dist == "nb") {
      s_strip <- rnbinom_zt(n_strip,
                            mu   = p$group_size_nb$mu,
                            size = p$group_size_nb$size)
    }
    # Per-group sigma under the species' detection function
    if (p$use_size_covar == 1L) {
      sigma_g <- p$sigma_det * exp(p$beta_size_truth * (s_strip - p$s_centre))
    } else {
      sigma_g <- rep(p$sigma_det, n_strip)
    }
    p_det <- exp(-x_true^2 / (2 * sigma_g^2))
    keep  <- runif(n_strip) < p_det
    if (any(keep)) {
      detect_rows[[i]] <- data.frame(
        seg_id   = segments$seg_id[i],
        distance = x_true[keep],
        size     = s_strip[keep]
      )
    }
  }
  obs <- do.call(rbind, detect_rows)
  if (is.null(obs)) {
    obs <- data.frame(seg_id = integer(), distance = numeric(), size = integer())
  }

  seg_count <- tabulate(obs$seg_id, nbins = n_seg_total)

  cat(sprintf("\n  groups in strip (truth): %d\n", sum(n_groups_in_strip)))
  cat(sprintf("  groups detected         : %d (%.1f%% of strip)\n",
              nrow(obs), 100 * nrow(obs) / max(sum(n_groups_in_strip), 1L)))
  cat(sprintf("  observed group sizes    : min=%d, mean=%.1f, max=%d\n",
              min(obs$size), mean(obs$size), max(obs$size)))
  cat(sprintf("  segments with >= 1 detection: %d / %d\n",
              sum(seg_count > 0), n_seg_total))

  if (nrow(obs) < 10L) {
    warning(sprintf("Too few detections (%d) for %s - skipping fit.",
                    nrow(obs), p$common_name))
    next
  }

  # ------------- 4c. Stan data ------------------------------------------------

  stan_data <- list(
    n                       = nrow(obs),
    x                       = obs$distance,
    s                       = as.integer(obs$size),
    w                       = w,
    log_sigma_prior_mean    = p$log_sigma_prior_mean,
    log_sigma_prior_sd      = p$log_sigma_prior_sd,
    use_size_covar          = p$use_size_covar,
    s_centre                = p$s_centre,
    beta_size_prior_mean    = p$beta_size_prior_mean,
    beta_size_prior_sd      = p$beta_size_prior_sd,
    S_max                   = p$S_max,
    mu_s_prior_shape        = p$mu_s_prior_shape,
    mu_s_prior_rate         = p$mu_s_prior_rate,
    phi_s_prior_shape       = p$phi_s_prior_shape,
    phi_s_prior_rate        = p$phi_s_prior_rate,
    log_lambda_s_prior_mean = p$log_lambda_s_prior_mean,
    log_lambda_s_prior_sd   = p$log_lambda_s_prior_sd,
    n_seg                   = n_seg_total,
    seg_count               = as.integer(seg_count),
    seg_l                   = rep(seg_length, n_seg_total)
  )

  # ------------- 4d. Stan fit -------------------------------------------------

  init_fn <- function() {
    lam_init <- max(mean(stan_data$seg_count /
                         (stan_data$seg_l * 2 * w)), 1e-6)
    list(
      log_sigma    = p$log_sigma_prior_mean + rnorm(1, 0, 0.3),
      beta_size    = rnorm(1, 0, 0.01),
      mu_s         = max(p$mu_s_prior_shape / p$mu_s_prior_rate
                         + rnorm(1, 0, 0.5 * p$mu_s_prior_shape / p$mu_s_prior_rate),
                         0.5),
      phi_s        = runif(1, 0.5, 2),
      log_lambda_s = log(runif(1,
                               max(lam_init * 0.1, 1e-6),
                               lam_init * 1.9 + 1e-6))
    )
  }

  cat("\n  Fitting distance_hn_dens_v4.1.stan...\n")
  fit <- mod$sample(
    data              = stan_data,
    chains            = 4,
    parallel_chains   = 4,
    threads_per_chain = 1,
    iter_warmup       = 1000,
    iter_sampling     = 1000,
    seed              = 42,
    init              = init_fn,
    refresh           = 500,
    show_messages     = FALSE
  )
  invisible(fit$cmdstan_diagnose())

  # ------------- 4e. Extract draws + summarise --------------------------------

  draws <- fit$draws(format = "df")

  # Implied observed-conditional mean group size E[s | s > 0] under the
  # fitted zero-truncated NB(mu_s, phi_s). For NB with mean mu, dispersion
  # phi: P(s = 0) = (phi / (mu + phi))^phi.
  # E[s | s > 0] = mu / (1 - P(s=0)).
  # This is what the empirical group-size mean should match if the
  # zero-truncated NB is a good fit. mu_s itself is the LATENT
  # (unconditional) mean, which is < empirical mean when there's
  # truncation effect.
  p_zero_post <- (draws$phi_s / (draws$mu_s + draws$phi_s))^draws$phi_s
  mean_s_obs_draw <- draws$mu_s / (1 - p_zero_post)

  # D = lambda_s * E[s | s > 0]. Animal density per detected-group means.
  # (Slightly different from the model's `D = lambda_s * mu_s` if mu_s
  # is the latent NB mean, since lambda_s itself is the GROUP density,
  # i.e. one entry per group regardless of size).
  D_animals_draw <- draws$lambda_s * mean_s_obs_draw

  param_truths <- tibble(
    param = c("sigma (km)",
              "beta_size",
              "mu_s (latent NB mean)",
              "E[s|s>0] (observed-cond. mean)",
              "lambda_s (groups/km^2)",
              "D (animals/km^2)"),
    truth = c(p$sigma_det,
              if (p$use_size_covar == 1L) p$beta_size_truth else NA_real_,
              # The "truth" for mu_s (latent NB mean) is unobservable in
              # general; we leave it NA. The empirical mean of the pool
              # is the truth for E[s | s > 0].
              NA_real_,
              p$mean_group_size,
              mean(lambda_groups),
              mean(lambda_animals))
  )

  param_summary <- bind_cols(param_truths, tibble(
    median = c(median(exp(draws$log_sigma)),
               median(draws$beta_size),
               median(draws$mu_s),
               median(mean_s_obs_draw),
               median(draws$lambda_s),
               median(D_animals_draw)),
    q025   = c(quantile(exp(draws$log_sigma), 0.025),
               quantile(draws$beta_size, 0.025),
               quantile(draws$mu_s, 0.025),
               quantile(mean_s_obs_draw, 0.025),
               quantile(draws$lambda_s, 0.025),
               quantile(D_animals_draw, 0.025)),
    q975   = c(quantile(exp(draws$log_sigma), 0.975),
               quantile(draws$beta_size, 0.975),
               quantile(draws$mu_s, 0.975),
               quantile(mean_s_obs_draw, 0.975),
               quantile(draws$lambda_s, 0.975),
               quantile(D_animals_draw, 0.975))
  ))
  cat("\n  Parameter recovery (truth = spatial mean for lambda / D):\n")
  print(knitr::kable(param_summary, digits = 4, format = "simple"))

  # ------------- 4f. Plots ----------------------------------------------------

  sp_colour <- if (sp_key == "humpback") "#3B528B" else "#5DC863"

  # (A) Density surface scatter at segment midpoints
  p_density <- ggplot(
      segments |> dplyr::mutate(lambda_animals = lambda_animals),
      aes(X_mid, Y_mid, colour = lambda_animals)) +
    geom_point(size = 1.0, alpha = 0.85) +
    scale_colour_viridis_c(name = expression(lambda ~ "(animals/km"^2 * ")"),
                           trans = "log10") +
    coord_fixed(xlim = c(0, X_km_max), ylim = c(0, Y_km_max), expand = FALSE) +
    labs(title    = sprintf("%s: simulated density at segment midpoints",
                            p$common_name),
         subtitle = "Each point = one 10-km transect segment, coloured by truth lambda",
         x = "Easting (km)", y = "Northing (km)") +
    theme_bw(base_size = 10) +
    theme(plot.title = element_text(face = "bold", size = 11))

  # (B) Detection-distance histogram + posterior median HN
  log_sigma_post <- median(draws$log_sigma)
  beta_post      <- median(draws$beta_size)
  if (p$use_size_covar == 1L) {
    sigma_post_at_mu <- exp(log_sigma_post +
                            beta_post * (median(draws$mu_s) - p$s_centre))
  } else {
    sigma_post_at_mu <- exp(log_sigma_post)
  }
  esw_post <- sigma_post_at_mu * sqrt(pi/2) *
              erf(w / (sigma_post_at_mu * sqrt(2)))
  esw_truth <- p$sigma_det * sqrt(pi/2) * erf(w / (p$sigma_det * sqrt(2)))

  p_hist <- ggplot(obs, aes(x = distance)) +
    geom_histogram(aes(y = after_stat(density)), bins = 20,
                   fill = "lightblue", colour = "white") +
    stat_function(fun = function(x) {
      exp(-x^2 / (2 * sigma_post_at_mu^2)) / esw_post
    }, colour = "red", linewidth = 1) +
    stat_function(fun = function(x) {
      exp(-x^2 / (2 * p$sigma_det^2)) / esw_truth
    }, colour = "darkgrey", linetype = "dashed", linewidth = 0.8) +
    labs(title    = sprintf("%s: detection function recovery",
                            p$common_name),
         subtitle = sprintf("Red = posterior median HN at mean group size (sigma=%.2f); grey dashed = truth (sigma=%.2f)",
                            sigma_post_at_mu, p$sigma_det),
         x = "Detection distance (km)", y = "Density") +
    theme_bw(base_size = 10) +
    theme(plot.title = element_text(face = "bold", size = 11))

  # (C) Parameter recovery scatter
  param_plot_df <- param_summary |> dplyr::filter(!is.na(truth))
  param_plot_df$param <- factor(param_plot_df$param,
                                 levels = param_plot_df$param)

  p_recovery <- ggplot(param_plot_df,
                       aes(x = param,
                           y = median,
                           ymin = q025, ymax = q975)) +
    geom_errorbar(width = 0.15, colour = sp_colour, linewidth = 0.8) +
    geom_point(colour = sp_colour, size = 3) +
    geom_point(aes(y = truth), colour = "red", shape = 4, size = 3, stroke = 1) +
    facet_wrap(~param, scales = "free", nrow = 1) +
    labs(title    = sprintf("%s: parameter recovery", p$common_name),
         subtitle = "Posterior median +/- 95% CI (coloured); red x = truth",
         x = NULL, y = NULL) +
    theme_bw(base_size = 10) +
    theme(plot.title  = element_text(face = "bold", size = 11),
          axis.text.x = element_blank(),
          axis.ticks.x = element_blank(),
          strip.text  = element_text(size = 9))

  # (D) Prior vs posterior density of D = lambda * mu_s
  truth_D <- mean(lambda_animals)

  # Sample from prior numerically: log_lambda_s ~ N, mu_s ~ Gamma
  n_prior_draws <- 5000L
  lambda_prior  <- exp(rnorm(n_prior_draws,
                             p$log_lambda_s_prior_mean,
                             p$log_lambda_s_prior_sd))
  mu_s_prior    <- rgamma(n_prior_draws,
                          shape = p$mu_s_prior_shape,
                          rate  = p$mu_s_prior_rate)
  D_prior_draws <- lambda_prior * mu_s_prior

  # Restrict the plot range to a sensible window so we can see both
  # densities. Use the joint quantile range.
  D_combined <- c(D_prior_draws, D_animals_draw)
  D_lo  <- max(quantile(D_combined, 0.005), 0)
  D_hi  <- max(quantile(D_combined, 0.995),
               1.5 * max(truth_D, median(D_animals_draw)))

  prior_post_df <- bind_rows(
    tibble(D = D_prior_draws, dist = "prior"),
    tibble(D = D_animals_draw, dist = "posterior")
  ) |>
    dplyr::filter(D >= D_lo, D <= D_hi)

  p_prior_post <- ggplot(prior_post_df, aes(x = D, fill = dist, colour = dist)) +
    geom_density(alpha = 0.32, linewidth = 0.8) +
    geom_vline(xintercept = truth_D, colour = "red",
               linetype = "dashed", linewidth = 0.7) +
    scale_fill_manual  (values = c(prior = "grey60",     posterior = sp_colour)) +
    scale_colour_manual(values = c(prior = "grey40",     posterior = sp_colour)) +
    coord_cartesian(xlim = c(D_lo, D_hi)) +
    labs(title    = sprintf("%s: prior vs posterior density of D (animals/km^2)",
                            p$common_name),
         subtitle = sprintf("Red dashed = simulated truth = %.4f. Prior on D induced by Normal(log_lambda_s) x Gamma(mu_s).",
                            truth_D),
         x = expression(D ~ "(animals/km"^2 * ")"),
         y = "density",
         fill = NULL, colour = NULL) +
    theme_bw(base_size = 10) +
    theme(plot.title    = element_text(face = "bold", size = 11),
          plot.subtitle = element_text(size = 9, colour = "grey40"),
          legend.position = "top")

  combined <- (p_density / (p_hist | p_prior_post)) /
              p_recovery +
              plot_layout(heights = c(2, 1.4, 1)) +
              plot_annotation(
                title    = sprintf("Distance sampling pipeline (v4.1) -- %s",
                                   p$common_name),
                subtitle = sprintf("HN(sigma=%.2f km, use_size_covar=%d), w=%.2f km. %d transects x %d segments x 10 km. %d detections.",
                                   p$sigma_det, p$use_size_covar, w,
                                   n_transects, n_seg_per_transect,
                                   nrow(obs)),
                theme = theme(plot.title    = element_text(face = "bold",
                                                           size = 13),
                              plot.subtitle = element_text(size = 10,
                                                           colour = "grey40"))
              )

  out_pdf <- file.path(OUTPUT_DIR,
                       sprintf("distance_v4.1_%s.pdf", sp_key))
  grDevices::cairo_pdf(out_pdf, width = 11, height = 11)
  print(combined)
  invisible(dev.off())
  cat(sprintf("  Saved %s\n", out_pdf))

  # Save fit + sim metadata
  saveRDS(list(
    sp_key            = sp_key,
    sp_params         = p,
    w                 = w,
    transect_Y        = transect_Y,
    seg_length        = seg_length,
    segments          = segments,
    f_seg             = f_seg,
    lambda_animals    = lambda_animals,
    lambda_groups     = lambda_groups,
    n_groups_in_strip = n_groups_in_strip,
    obs               = obs,
    seg_count         = seg_count,
    stan_data         = stan_data,
    fit               = fit,
    param_summary     = param_summary
  ), file.path(OUTPUT_DIR, sprintf("distance_v4.1_%s.rds", sp_key)))

  results[[sp_key]] <- param_summary |>
    dplyr::mutate(species = p$common_name) |>
    dplyr::filter(!is.na(truth) | param == "beta_size")
}

# -----------------------------------------------------------------------------
# 5. Combined summary
# -----------------------------------------------------------------------------

if (length(results) > 0L) {
  cat("\n\n======================================================\n")
  cat("=== Combined recovery table\n")
  cat("======================================================\n\n")

  combined_summary <- do.call(rbind, results) |>
    dplyr::select(species, param, truth, median, q025, q975)
  print(knitr::kable(combined_summary, digits = 4, format = "simple"))
  write_csv(combined_summary,
            file.path(OUTPUT_DIR, "distance_v4.1_recovery.csv"))
}

cat(sprintf("\n=== Done. Outputs written to %s ===\n", OUTPUT_DIR))
for (f in list.files(OUTPUT_DIR)) cat(sprintf("  %s\n", f))
